#' @title A FLStock class object
#'
#' @description Defines and fill a FLStock object using the information provided by the main function Population.Modeling.
#'
#' @param Pop.Mod A list containing the components returned by Population.Modeling function (main function).
#'
#'
#' @return {The FLStock object (see R package FLCore) corresponding to the simulated population generated by Population.Modeling function.}
#' @author
#' \itemize{
#' \item{Marta Cousido-Rocha}
#' \item{Santiago Cerviño López}
#' }
#' @export

FLStock.from.Rfishpop=function(Pop.Mod){

  # First we read the dimensions

  l_ages=dim(Pop.Mod$Matrices$N)[1]
  l_years=dim(Pop.Mod$Matrices$N)[2]
  l_iters=dim(Pop.Mod$Matrices$N)[3]

  # We read the years and ages

  years=as.numeric(colnames(Pop.Mod$Matrices$F))
  ages=as.numeric(rownames(Pop.Mod$Matrices$F))

  # 1. catch
  C=Sum.Pop.Mod(Pop.Mod,c("C"))$C


  FLR_C=FLCore::FLQuant(C,iter=l_iters,quant="age", units="kg",
                dim=c(1,l_years))
  dimnames(FLR_C)$year=years

  # To access each iter use FLR_C@Data

  # 2. catch.n

  C_N=Pop.Mod$Matrices$C_N

  FLR_C_N=FLCore::FLQuant(C_N,iter=l_iters,quant="age", units="1",
                dim=c(l_ages,l_years))
  dimnames(FLR_C_N)$year=years
  dimnames(FLR_C_N)$age=ages

  # Now, we can create a FLStock

  stk <- FLCore::FLStock(catch.n = FLR_C_N,
                 name = "My Rfishpop",
                 desc = "A stock from Rfishpop simulator")
  #summary(stk)
  FLCore::catch(stk)=FLR_C

  # 3. catch.wt

  C_W=Pop.Mod$Matrices$C_W

  FLR_C_W=FLCore::FLQuant(C_W,iter=l_iters,quant="age", units="kg",
                  dim=c(l_ages,l_years))
  dimnames(FLR_C_W)$year=years
  dimnames(FLR_C_W)$age=ages

  FLCore::catch.wt(stk)=FLR_C_W

  # 4. discards

  FLR_D=FLCore::FLQuant(0,iter=l_iters,quant="age", units="kg",
                dim=c(1,l_years))
  dimnames(FLR_D)$year=years

  FLCore::discards(stk)=FLR_D
  # 5. discards.n

  FLR_D_N=FLCore::FLQuant(0,iter=l_iters,quant="age", units="1",
                  dim=c(l_ages,l_years))
  dimnames(FLR_D_N)$year=years
  dimnames(FLR_D_N)$age=ages

  FLCore::discards.n(stk)=FLR_D_N

  # 6. discards.wt



  FLR_D_W=FLCore::FLQuant(0,iter=l_iters,quant="age", units="kg",
                  dim=c(l_ages,l_years))
  dimnames(FLR_D_W)$year=years
  dimnames(FLR_D_W)$age=ages

  FLCore::discards.wt(stk)=FLR_D_W

  # 7. landings
  C=Sum.Pop.Mod(Pop.Mod,c("C"))$C


  FLR_L=FLCore::FLQuant(C,iter=l_iters,quant="age", units="kg",
                dim=c(1,l_years))
  dimnames(FLR_L)$year=years

  FLCore::landings(stk)=FLR_L

  # 8. landings.n

  C_N=Pop.Mod$Matrices$C_N

  FLR_L_N=FLCore::FLQuant(C_N,iter=l_iters,quant="age", units="1",
                  dim=c(l_ages,l_years))
  dimnames(FLR_L_N)$year=years
  dimnames(FLR_L_N)$age=ages

  FLCore::landings.n(stk)=FLR_L_N

  # 9. landings.wt

  C_W=Pop.Mod$Matrices$C_W

  FLR_L_W=FLCore::FLQuant(C_W,iter=l_iters,quant="age", units="kg",
                  dim=c(l_ages,l_years))
  dimnames(FLR_L_W)$year=years
  dimnames(FLR_L_W)$age=ages

  FLCore::landings.wt(stk)=FLR_L_W


  # 10. stock
  BIO=Sum.Pop.Mod(Pop.Mod,c("BIO"))$BIO


  FLR_S=FLCore::FLQuant(BIO,iter=l_iters,quant="age", units="kg",
                dim=c(1,l_years))
  dimnames(FLR_S)$year=years

  FLCore::stock(stk)=FLR_S

  # 11. stock.n

  N=Pop.Mod$Matrices$N

  FLR_S_N=FLCore::FLQuant(N,iter=l_iters,quant="age", units="1",
                  dim=c(l_ages,l_years))
  dimnames(FLR_S_N)$year=years
  dimnames(FLR_S_N)$age=ages

  FLCore::stock.n(stk)=FLR_S_N

  # 12. stock.wt

  W=Pop.Mod$Matrices$W

  FLR_S_W=FLCore::FLQuant(W,iter=l_iters,quant="age", units="kg",
                  dim=c(l_ages,l_years))
  dimnames(FLR_S_W)$year=years
  dimnames(FLR_S_W)$age=ages

  FLCore::stock.wt(stk)=FLR_S_W

  # 13. m

  M=Pop.Mod$Matrices$M

  FLR_M=FLCore::FLQuant(M,iter=l_iters,quant="age", units="m",
                  dim=c(l_ages,l_years))
  dimnames(FLR_M)$year=years
  dimnames(FLR_M)$age=ages

  FLCore::m(stk)=FLR_M

  # 14. mat

  Mat=Pop.Mod$Matrices$Mat

  FLR_Mat=FLCore::FLQuant(Mat,iter=l_iters,quant="age", units="",
                dim=c(l_ages,l_years))
  dimnames(FLR_Mat)$year=years
  dimnames(FLR_Mat)$age=ages

  FLCore::mat(stk)=FLR_Mat

  # 15. harvest

  F=Pop.Mod$Matrices$F

  FLR_F=FLCore::FLQuant(F,iter=l_iters,quant="age", units="f",
                  dim=c(l_ages,l_years))
  dimnames(FLR_F)$year=years
  dimnames(FLR_F)$age=ages

  FLCore::harvest(stk)=FLR_F

  # 16. range


  stk@range[6]=Pop.Mod$Info$minFage
  stk@range[7]=Pop.Mod$Info$maxFage


  # 17. harvest.spwn


  FLR_F_S=FLCore::FLQuant(0,iter=l_iters,quant="age", units="f",
                dim=c(l_ages,l_years))
  dimnames(FLR_F_S)$year=years
  dimnames(FLR_F_S)$age=ages

  FLCore::harvest.spwn(stk)=FLR_F_S

  # 15. m.spwn


  FLR_M_S=FLCore::FLQuant(0,iter=l_iters,quant="age", units="f",
                dim=c(l_ages,l_years))
  dimnames(FLR_M_S)$year=years
  dimnames(FLR_M_S)$age=ages

  FLCore::m.spwn(stk)=FLR_M_S

  return(stk)
}



